netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	172.217.165.142
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	142.250.64.78
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	142.250.64.110
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	172.217.3.110
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	172.217.6.206
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	172.217.7.14
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	172.217.9.238
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	172.217.10.14
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	172.217.10.78
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	172.217.10.110
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	172.217.10.142
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	172.217.10.238
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	172.217.12.142
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	172.217.12.174
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	172.217.12.206
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	172.217.8.174
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	172.217.8.206
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	172.217.4.206
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	172.217.4.78
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	172.217.6.14
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	172.217.4.238
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	172.217.0.14
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	172.217.9.46
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	172.217.9.78
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	216.58.192.142
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	216.58.192.174
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	172.217.4.46
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	172.217.5.14
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	172.217.1.46
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	172.217.10.46
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	172.217.10.78
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	172.217.10.110
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	172.217.10.142
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	172.217.3.110
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	172.217.12.142
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	172.217.6.206
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	172.217.7.14
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	172.217.10.238
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	172.217.11.14
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	172.217.11.46
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	172.217.12.174
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	172.217.12.206
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	142.250.64.78
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	142.250.64.110
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	172.217.165.142
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	172.217.1.46
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	172.217.8.174
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	172.217.8.206
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	216.58.192.206
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	172.217.4.206
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	172.217.4.78
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	172.217.6.14
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	172.217.4.238
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	172.217.0.14
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	172.217.9.78
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	216.58.192.142
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	172.217.4.46
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	172.217.5.14
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	172.217.18.14
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	216.58.212.142
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	172.217.23.110
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	216.58.206.14
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	172.217.21.238
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	172.217.22.14
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	172.217.16.206
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	172.217.16.174
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	142.250.74.206
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	216.58.208.46
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	172.217.21.206
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	216.58.212.174
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	172.217.23.174
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	172.217.23.142
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	216.58.205.238
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	172.217.16.142
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	172.217.164.206
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	172.217.164.238
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	172.217.0.238
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	172.217.1.174
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	172.217.1.14
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	172.217.165.14
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	172.217.11.14
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	172.217.11.46
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	172.217.12.174
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	172.217.12.206
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	142.250.64.78
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	142.250.64.110
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	172.217.165.142
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	172.217.10.14
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	172.217.10.78
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	172.217.10.142
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	172.217.3.110
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	172.217.12.142
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	172.217.6.206
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	172.217.6.238
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	172.217.7.14
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	172.217.10.238
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	172.217.170.78
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	172.217.170.46
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	216.58.223.142
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	172.217.170.14
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	172.217.17.142
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	172.217.19.206
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	216.58.214.14
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	172.217.168.206
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	216.58.208.110
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	172.217.20.78
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	216.58.211.110
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	172.217.168.238
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	172.217.17.78
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	172.217.20.110
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	216.58.214.78
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	216.58.209.238
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	172.217.18.206
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	216.58.206.238
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	216.58.201.238
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	216.58.215.46
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	216.58.198.206
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	172.217.22.142
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	216.58.204.142
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	216.58.204.110
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	142.250.74.238
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	216.58.213.142
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	172.217.19.238
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	216.58.213.78
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	172.217.168.174
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	216.58.211.238
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	216.58.211.46
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	216.58.209.78
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	172.217.17.14
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	216.58.201.174
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	172.217.168.78
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	216.58.215.238
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	172.217.168.14
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	172.217.168.46
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	173.194.222.190
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	74.125.205.190
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	173.194.73.93
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	64.233.163.91
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	64.233.162.190
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	64.233.164.136
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	64.233.162.93
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	64.233.165.190
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	64.233.162.91
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	173.194.222.93
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	173.194.222.91
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	64.233.165.136
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	64.233.165.91
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	64.233.165.93
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	173.194.73.91
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	64.233.162.136
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	216.58.210.238
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	216.58.211.174
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	216.58.210.46
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	216.58.204.14
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	216.58.206.110
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	216.58.206.142
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	216.58.204.238
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	216.58.204.46
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	216.58.204.78
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	216.58.213.14
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	172.217.169.14
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	216.58.212.238
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	172.217.169.46
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	172.217.169.78
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	216.58.210.206
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	172.217.21.174
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	172.217.22.174
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	216.58.207.206
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	216.58.207.238
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	172.217.21.142
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	172.217.20.46
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	172.217.16.14
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	172.217.16.46
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	216.58.215.78
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	216.58.215.110
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	216.58.209.14
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	216.58.208.206
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	216.58.217.14
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	172.217.5.174
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	172.217.15.14
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	216.58.195.238
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	216.58.193.14
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	172.217.30.78
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	172.217.30.110
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	172.217.172.206
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	172.217.28.78
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	172.217.162.142
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	172.217.162.206
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	172.217.30.174
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	172.217.29.142
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	172.217.30.46
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	172.217.173.78
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	172.217.173.110
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	172.217.172.142
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	216.58.202.14
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	172.217.28.142
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	172.217.28.238
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	172.217.29.14
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	74.125.24.136
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	74.125.24.190
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	74.125.24.91
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	74.125.130.91
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	172.217.194.93
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	172.217.194.190
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	172.217.194.136
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	172.217.194.91
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	216.58.221.78
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	172.217.11.46
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	172.217.6.238
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	142.250.64.110
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	172.217.7.14
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	172.217.10.238
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	172.217.12.206
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	172.217.6.206
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	172.217.10.78
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	172.217.12.174
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	172.217.10.110
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	172.217.10.46
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	172.217.12.142
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	142.250.64.78
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	172.217.165.142
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	172.217.3.110
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	74.125.200.190
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	74.125.24.190
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	74.125.200.93
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	74.125.24.91
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	172.217.194.136
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	172.217.194.93
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	74.125.68.190
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	172.217.194.190
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	172.217.194.91
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	74.125.130.93
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	74.125.24.93
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	172.217.174.110
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	172.217.161.46
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	172.217.175.238
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	172.217.31.142
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	216.58.197.174
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	172.217.175.110
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	172.217.25.110
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	216.58.197.142
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	172.217.161.78
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	216.58.220.110
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	172.217.31.174
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	216.58.197.206
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	172.217.175.46
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	172.217.24.142
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	172.217.25.78
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	216.58.220.142
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	216.58.199.14
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	216.58.200.14
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	172.217.24.206
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	216.58.220.206
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	172.217.161.142
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	172.217.163.238
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	216.58.221.238
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	216.58.199.110
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	172.217.25.14
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	172.217.26.142
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	172.217.161.174
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	216.58.200.78
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	172.217.24.78
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	172.217.174.206
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	216.58.197.110
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	172.217.169.174
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	172.217.17.206
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	216.58.214.142
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	172.217.169.142
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	172.217.17.238
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	172.217.169.110
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	216.58.206.206
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	216.58.212.46
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	216.58.206.174
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	172.217.169.206
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	216.58.199.142
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	172.217.166.174
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	172.217.160.174
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	172.217.167.174
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	172.217.174.238
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	172.217.27.206
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	142.250.67.238
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	172.217.166.46
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	216.58.203.142
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	216.58.203.46
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	216.58.196.78
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	216.58.203.14
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	172.217.160.206
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	172.217.174.78
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	216.58.203.174
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	172.217.21.46
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	172.217.19.14
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	216.58.208.238
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	172.217.19.174
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	74.125.193.136
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	74.125.193.93
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	74.125.193.91
netsh advfirewall firewall add rule name="BlockYT" protocol=any dir=in action=block remoteip=	74.125.193.190

